language: node_js
node_js:
- stable
script:
- npm run build
- npm run coverage
- sonar-scanner
dist: trusty
addons:
  sonarcloud:
    organization: jammymalina
    token:
      secure: W06dn3ZpKogKN84HgokzJwHZSzXdqlK5xzlHnM+omilk72eJSh4Bw+3+RQEh2N5bOQf6Iwt+Lt7xJM5gPJ7qS2XQbLQz7bs3aCt+Qwa8doWS9pGsJp6+VTIjZTO42rvHZzBHSlAnt750uhvhFoDYfzAmtyjeEo0iN/snR1M8yY1b6DVTBjijiEPH6OdWGnFCcwH7aLo9/Sc2zf/HvAFleECPFgG+swuPJxGylclm+dTRQ1vgvqDKxpXcTiuQb96p8GwRw2yHo9i8uy2+6/gJVtt1MtR/O1OBgkBmNiWWOd7YsN7foHXPiI9WCTNh63aBAyqqw2qS/Dl0Cnwk6jX4DWU8algvMVv6xPuRxfmjrcIy+i2jGNpEhjJQ0ztC9qTOMCV6sZQiTzQUHcDOSRQNzzNM9Yyzk4eA3hr61IpEHXzijRmiY/wAT2XrDS73fyZlrOlYYCXkwZpmqd09RzhPn8AvHmLnNv8RA5eVwqfXLT3ncq+FfCcaizKCfQPY1vOBFtx7stfzf8RPdNyZmCdd9oTKqnuwv8+v2rdffqqCxWShx3XqnjKLJVYCjhLFGBN2oGvDkzxmTIT0XO9Dj3cf+1bCwmLOQ+APJjxesgDJ+Mq4geZPhQKllejHugEo7aUS4TcOM0Kd72JZHVuwdumnKaXJJj9lhY0ntdipXiymjKo=
