language: node_js
node_js:
- stable
script:
- npm run build
- npm run coverage
- sonar-scanner
dist: trusty
addons:
  sonarcloud:
    organization: jammymalina
    token:
      secure: FFKdMpnM4XVgELkcqJNphz/+sLe0FK+ib+OQt0ycz3V4ux3BEZ0K4t7h0c2dVfd4ydfu6kSAUYFaE9qGOspcYeSsORsqavWhMSQvSQrx1FuArLcyrQspW9Ysxv6+TEP4LU0cbp4Li60rIBafY0rnFVEC/yvsNoM5ckAQPm8CS84GIA85o646dve2QCLxoDsqgQ105Auull70+Vw8paeDn9qrEdb0TPnEGwVL2P3UAFrqOCio+4PN1QxTU0VYQNIMIQMt1UBlUrECv4yTsi1Y6w93oUX269WgJ8UgEzIrHBhxiBgQX+bTAO/KfnrSWwCXBUODPQQGPx9UzUsim1WbkfGXDcXpMYEQ+3xvaA0hAzqk6iN8d1KhHB3FNOhRN3g644TorAPu8ZaKAZ6AxCH+4vAEpJd19VWO+t7U4hZwBjZxNPHnWxwZ7kHLBPC/bWf9coHL7Wof4y4j87iUkbhBZu/k+SJSvw7FURy7/VtX0fXJQl/cCyEnksakhOPGvlej00ug421MJqtlJ0IWfS2hK/2baIaJywB9/5jhaRzk+OlNB+C1OkQYx5SAwVwkssbQki9XeJdtW4RzSncUTkymNT7A4CIdKqHHeKE3G58T0h4oQNmXVcKYU5m98+8awikP1ZZeG/dFIlrDjnLq7ryTzeJjk7wYrAdiBnRTGO0Za9o=
